language: node_js
node_js:
- 6.9.1
- 7.1.0
cache:
  directories:
    - node_modules
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - wget "http://chromedriver.storage.googleapis.com/2.25/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 2
install:
- sudo pip install -r requirements.txt
- sudo python setup.py develop
- (cd tests/create-react-app && yarn install)
script:
- pybot test.robot
notifications:
  email:
  - stollenwerk@kitconcept.com
